#
# Config

config:

  # Limit of jobs each player.
  limit-jobs: 3

  formula:
  # Formula por max xp:
    max-xp: %j * 5

#
# List of jobs.
jobs:

  # Miner
  miner:

    # Type [PLAYER_BREAK_BLOCK, PLAYER_PLACE_BLOCK, PLAYER_KILL_ENTITY]
    type: PLAYER_BREAK_BLOCK

    # List of items
    items:
      - COBBLESTONE