#
# Config

config:

  # Limit of jobs each player.
  limit-jobs: 3

  # Disable creative mode:
  disable-creative: true

  # Disable silk touch:
  disable-silk-touch: true

  # Set max level to get.
  max-level-jobs: 200

  multiplier:

    # To broadcast the multiplier. Put 'none' to disable this option.
    broadcast: none

    # Default multiplier
    default: 1.0

    # Group multiplier [Need a plugin permision]:
    group:
  #     vip: 2.0
  #     vip+: 3.0

  formula:

    # Formula for gain money per level:
    gain-money: "%money% * %level%"

    # Formula for gain xp per level:
    gain-xp: "%xp% * %level%"

    # Formula for max xp:
    max-xp: "(%level% * %level%) * 10"

  action-bar:

    # Format to gain rewards:
    gain-rewards: "&a+%money%$ &8- &f+%xp%XP"

  # Reward when you increase a level:
  rewards:

    config:

      # To enable the option.
      enabled: false

    # This path is a the level when you increase:
    10:
      # All formats: [ADD-MONEY] [BROADCAST] [COMMAND]
      format:
        - "[ADD-MONEY] 500"
        - "[BROADCAST] &aThe player &a%player% won the level 10"
        - "[COMMAND] give %player% diamond "



#
# List of jobs.
jobs:

  # Miner job:
  miner:

    # Name of the job:
    name: "Miner"

    # Type [PLAYER_BREAK_BLOCK, PLAYER_PLACE_BLOCK, PLAYER_KILL_ENTITY]
    type: PLAYER_BREAK_BLOCK

    # List of items
    items:

      # Format: money: GAIN_MONEY, xp: GAIN_XP_JOB:

      STONE:

        money: 1
        xp: 1

      COAL_ORE:
        money: 2
        xp: 2


      IRON_ORE:
        money: 2
        xp: 2

      GOLD_ORE:
        money: 3
        xp: 3

      DIAMOND_ORE:
        money: 5
        xp: 5

      EMERALD_ORE:
        money: 4
        xp: 4

      REDSTONE_ORE:
        money: 3
        xp: 4

      LAPIZ_ORE:
        money: 3
        xp: 3

  # Woodcutter jobb
  woodcutter:
    name: "Woodcutter"

    # Type [PLAYER_BREAK_BLOCK, PLAYER_PLACE_BLOCK, PLAYER_KILL_ENTITY]
    type: PLAYER_BREAK_BLOCK

    # List of items
    items:
      ACACIA_LOG:

        money: 1
        xp: 1

      BIRCH_LOG:

        money: 1
        xp: 1

      DARK_OAK_LOG:

        money: 1
        xp: 1

      JUNGLE_LOG:

        money: 1
        xp: 1

      MANGROVE_LOG:

        money: 1
        xp: 1

      OAK_LOG:

        money: 1
        xp: 1

  # Builder job
  builder:
    # Name of the job:
    name: "Builder"

    # Type [PLAYER_BREAK_BLOCK, PLAYER_PLACE_BLOCK, PLAYER_KILL_ENTITY]
    type: PLAYER_PLACE_BLOCK

    # List of items
    items:
      # Format: money: GAIN_MONEY, xp: GAIN_XP_JOB:

      STONE:

        money: 1
        xp: 1

      ACACIA_WOOD:

        money: 1
        xp: 1

      BIRCH_WOOD:

        money: 1
        xp: 1

      DARK_OAK_WOOD:

        money: 1
        xp: 1

      JUNGLE_WOOD:

        money: 1
        xp: 1

      MANGROVE_WOOD:

        money: 1
        xp: 1

      OAK_WOOD:

        money: 1
        xp: 1

      ACACIA_PLANKS:

        money: 1
        xp: 1

      BIRCH_PLANKS:

        money: 1
        xp: 1

      DARK_OAK_PLANKS:

        money: 1
        xp: 1

      JUNGLE_PLANKS:

        money: 1
        xp: 1

      MANGROVE_PLANKS:

        money: 1
        xp: 1

      OAK_PLANKS:

        money: 1
        xp: 1

      QUARTZ:

        money: 2
        xp: 2

      DIAMOND_BLOCK:
        money: 10
        xp: 10

      EMERALD_BLOCK:
        money: 8
        xp: 8

      IRON_BLOCK:
        money: 5
        xp: 5

      REDSTONE_BLOCK:
        money: 5
        xp: 5

      GOLD_BLOCK:
        money: 5
        xp: 5

      CARBON_BLOCK:
        money: 2
        xp: 2

  # Hunter job
  hunter:
    # Name of the job:
    name: "Hunter"

    # Type [PLAYER_BREAK_BLOCK, PLAYER_PLACE_BLOCK, PLAYER_KILL_ENTITY]
    type: PLAYER_KILL_ENTITY

    # List of items
    items:
      # Format: money: GAIN_MONEY, xp: GAIN_XP_JOB:

      PLAYER:
        money: 10
        xp: 10

      PIG:
        money: 5
        xp: 5

      COW:
        money: 5
        xp: 5

      MUSHROM_COW:
        money: 5
        xp: 5

      ZOMBIE:
        money: 5
        xp: 5

      SKELETON:
        money: 5
        xp: 5

      SPIDER:
        money: 5
        xp: 5

      CREEPER:
        money: 5
        xp: 5

